# Generated by Django 2.2.6 on 2020-06-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_borrowed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='request_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
