# Generated by Django 2.2.6 on 2020-06-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200606_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
